# The URL the site will be built for
base_url = "https://paddler.intentee.com"

description = "Open-source LLMOps platform for hosting and scaling AI in your own infrastructure."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
external_links_target_blank = true
highlight_code = true
# highlight_theme = "cheerfully-light"
highlight_themes_css = [
    { theme = "subway-moscow", filename = "syntax-theme-light.css" },
]
highlight_theme = "css"

[slugify]
paths = "on"
